### PR TITLE
Close #68 Close #57 Close #59 Close #63 Close #65 Close #70

### LINKED ISSUE #57: Palm Leaves destroy blocks on spawn.

### LINKED ISSUE #59: Redstone Ore (Limestone) drops itself instead of Redstone Dust.

### LINKED ISSUE #63: Strange Sand lacks gravity.

### LINKED ISSUE #65: You can fish in Atum.

### LINKED ISSUE #68: Palm Trees grow with only a single Bonemeal.

### LINKED ISSUE #70: Ptah's Decadence drops an extra Diamond in addition to an Ore block with Silk Touch. (Causing infinite Diamond loop.)

### PR DESCRIPTION
**Pull request by jaredlll08**

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Nice work Jared!

**Comment by Shadowclaimer** [comment]
Very awesome!

**Comment by GirafiStudios** [comment]
@Shadowclaimer would it be possible for you to jump on IRC? I have a question related to #53

**Comment by jaredlll08** [comment]
This also closes #56

**Comment by jaredlll08** [comment]
Palm trees now have a 1/7 chance to grow with bonemeal.
Palm leaves check if the leaves overwrite a block, if it does, it does not generate it.
Atum Redstone Ore now drops Vanilla redstone.
Strange Sand now obeys the law of gravity.
You cannot fish in Atum.
Made Ptah's Decadence check if it has silk touch, if it does, it does not drop the diamond.
Walls now keep their metadata.
Slabs now keep their metadata.
Fixed shading issues with Slabs and a few other blocks.
Relics don't reveal themselves until cleaned.
Portal block is now 2 pixels shorter.
changed portal texture.
Mummies give minor wither on hit.

**Pull request merged**
